// Asal public shakhsiyat (demo ke liye unclaimed public profiles).
// Sirf aam maloom, seedhi baatein: koi follower count, contact, email, phone ya quote nahi.
// professions / industries / topics = taxonomy slugs (taxonomyData.ts mein mojood)
export interface RealPerson {
  name: string
  slug: string
  // English Wikipedia article ka title (photo aur source ke liye)
  wikiTitle: string
  // wikiTitle ka article na mile to ye titles bhi try karo
  altWikiTitles?: string[]
  headline: string
  bio: string
  country: string
  professions: string[]
  industries: string[]
  topics: string[]
}

export const REAL_PEOPLE: RealPerson[] = [
  {
    name: 'Babar Azam',
    slug: 'babar-azam',
    wikiTitle: 'Babar_Azam',
    headline: 'Pakistani international cricketer and former national team captain',
    bio: 'Babar Azam is a Pakistani international cricketer. He has previously captained the Pakistan national team.',
    country: 'PK',
    professions: ['cricketer'],
    industries: ['sports'],
    topics: ['cricket'],
  },
  {
    name: 'Shahid Afridi',
    slug: 'shahid-afridi',
    wikiTitle: 'Shahid_Afridi',
    headline: 'Former Pakistan all-rounder and captain',
    bio: 'Shahid Afridi is a former Pakistan cricket all-rounder and captain. He is the founder of the Shahid Afridi Foundation.',
    country: 'PK',
    professions: ['cricketer'],
    industries: ['sports'],
    topics: ['cricket', 'philanthropy'],
  },
  {
    name: 'Arshad Nadeem',
    slug: 'arshad-nadeem',
    wikiTitle: 'Arshad_Nadeem',
    headline: 'Pakistani javelin thrower and Olympic champion',
    bio: 'Arshad Nadeem is a Pakistani javelin thrower. He won the Olympic gold medal in the javelin throw at the Paris 2024 Games.',
    country: 'PK',
    professions: ['athlete'],
    industries: ['sports'],
    topics: ['athletics', 'olympics'],
  },
  {
    name: 'Malala Yousafzai',
    slug: 'malala-yousafzai',
    wikiTitle: 'Malala_Yousafzai',
    headline: "Girls' education activist and Nobel Peace Prize laureate",
    bio: "Malala Yousafzai is a Pakistani activist for girls' education. She is the youngest person to have received the Nobel Peace Prize.",
    country: 'PK',
    professions: ['activist'],
    industries: ['education'],
    topics: ['education-reform', 'women-empowerment', 'human-rights'],
  },
  {
    name: 'Sharmeen Obaid-Chinoy',
    slug: 'sharmeen-obaid-chinoy',
    wikiTitle: 'Sharmeen_Obaid-Chinoy',
    headline: 'Pakistani filmmaker and two-time Academy Award winner',
    bio: 'Sharmeen Obaid-Chinoy is a Pakistani filmmaker. She has won two Academy Awards for her documentary films.',
    country: 'PK',
    professions: ['filmmaker'],
    industries: ['film-tv'],
    topics: ['documentary', 'film'],
  },
  {
    name: 'Mahira Khan',
    slug: 'mahira-khan',
    wikiTitle: 'Mahira_Khan',
    headline: 'Pakistani actress in television dramas and films',
    bio: 'Mahira Khan is a Pakistani actress. She is known for her work in television dramas and films.',
    country: 'PK',
    professions: ['actor'],
    industries: ['film-tv'],
    topics: ['drama', 'film'],
  },
  {
    name: 'Fawad Khan',
    slug: 'fawad-khan',
    wikiTitle: 'Fawad_Khan',
    headline: 'Pakistani actor and singer',
    bio: 'Fawad Khan is a Pakistani actor and singer. He is known for his roles in television and film.',
    country: 'PK',
    professions: ['actor'],
    industries: ['film-tv'],
    topics: ['drama', 'film'],
  },
  {
    name: 'Hania Aamir',
    slug: 'hania-aamir',
    wikiTitle: 'Hania_Aamir',
    headline: 'Pakistani actress and social media personality',
    bio: 'Hania Aamir is a Pakistani actress. She is also known as a social media personality.',
    country: 'PK',
    professions: ['actor'],
    industries: ['film-tv'],
    topics: ['drama', 'social-media'],
  },
  {
    name: 'Sajal Aly',
    slug: 'sajal-aly',
    wikiTitle: 'Sajal_Aly',
    headline: 'Pakistani actress in television dramas and films',
    bio: 'Sajal Aly is a Pakistani actress. She works in television dramas and films.',
    country: 'PK',
    professions: ['actor'],
    industries: ['film-tv'],
    topics: ['drama', 'film'],
  },
  {
    name: 'Atif Aslam',
    slug: 'atif-aslam',
    wikiTitle: 'Atif_Aslam',
    headline: 'Pakistani singer and playback artist',
    bio: 'Atif Aslam is a Pakistani singer. He is also known as a playback singer for films.',
    country: 'PK',
    professions: ['singer'],
    industries: ['music'],
    topics: ['pop-music'],
  },
  {
    name: 'Ali Zafar',
    slug: 'ali-zafar',
    wikiTitle: 'Ali_Zafar',
    headline: 'Pakistani singer-songwriter, actor and painter',
    bio: 'Ali Zafar is a Pakistani singer-songwriter and actor. He is also a painter.',
    country: 'PK',
    professions: ['singer', 'actor'],
    industries: ['music'],
    topics: ['pop-music', 'film'],
  },
  {
    name: 'Ducky Bhai',
    slug: 'ducky-bhai',
    wikiTitle: 'Ducky_Bhai',
    altWikiTitles: ['Saad_Ur_Rehman', 'Saad_ur_Rehman'],
    headline: 'Pakistani YouTuber and content creator',
    bio: 'Ducky Bhai, whose real name is Saad ur Rehman, is a Pakistani YouTuber and content creator.',
    country: 'PK',
    professions: ['youtuber'],
    industries: ['content-creation'],
    topics: ['comedy', 'social-media'],
  },
  {
    name: 'Zayn Malik',
    slug: 'zayn-malik',
    wikiTitle: 'Zayn_Malik',
    headline: 'British singer-songwriter and former member of One Direction',
    bio: 'Zayn Malik is a British singer-songwriter of Pakistani heritage. He is a former member of the band One Direction.',
    country: 'GB',
    professions: ['singer'],
    industries: ['music'],
    topics: ['pop-music'],
  },
  {
    name: 'Cristiano Ronaldo',
    slug: 'cristiano-ronaldo',
    wikiTitle: 'Cristiano_Ronaldo',
    headline: 'Portuguese footballer and national team captain',
    bio: 'Cristiano Ronaldo is a Portuguese professional footballer. He captains the Portugal national team.',
    country: 'PT',
    professions: ['footballer'],
    industries: ['sports'],
    topics: ['football', 'fitness'],
  },
  {
    name: 'Lionel Messi',
    slug: 'lionel-messi',
    wikiTitle: 'Lionel_Messi',
    headline: 'Argentine footballer and 2022 World Cup winner',
    bio: 'Lionel Messi is an Argentine professional footballer. He won the 2022 FIFA World Cup with Argentina.',
    country: 'AR',
    professions: ['footballer'],
    industries: ['sports'],
    topics: ['football'],
  },
  {
    name: 'Mohamed Salah',
    slug: 'mohamed-salah',
    wikiTitle: 'Mohamed_Salah',
    headline: 'Egyptian footballer and Liverpool forward',
    bio: 'Mohamed Salah is an Egyptian professional footballer. He plays as a forward for Liverpool.',
    country: 'EG',
    professions: ['footballer'],
    industries: ['sports'],
    topics: ['football'],
  },
  {
    name: 'Virat Kohli',
    slug: 'virat-kohli',
    wikiTitle: 'Virat_Kohli',
    headline: 'Indian international cricketer and former national team captain',
    bio: 'Virat Kohli is an Indian international cricketer. He has previously captained the India national team.',
    country: 'IN',
    professions: ['cricketer'],
    industries: ['sports'],
    topics: ['cricket', 'fitness'],
  },
  {
    name: 'Selena Gomez',
    slug: 'selena-gomez',
    wikiTitle: 'Selena_Gomez',
    headline: 'American singer, actress, producer and founder of Rare Beauty',
    bio: 'Selena Gomez is an American singer, actress and producer. She is the founder of the cosmetics brand Rare Beauty.',
    country: 'US',
    professions: ['singer', 'actor', 'entrepreneur'],
    industries: ['music'],
    topics: ['pop-music', 'makeup', 'mental-health'],
  },
  {
    name: 'Rihanna',
    slug: 'rihanna',
    wikiTitle: 'Rihanna',
    headline: 'Barbadian singer and founder of Fenty Beauty',
    bio: 'Rihanna is a Barbadian singer and businesswoman. She founded the brands Fenty Beauty and Savage X Fenty.',
    country: 'BB',
    professions: ['singer', 'entrepreneur'],
    industries: ['music'],
    topics: ['pop-music', 'makeup', 'fashion-trends'],
  },
  {
    name: 'Dwayne Johnson',
    slug: 'dwayne-johnson',
    wikiTitle: 'Dwayne_Johnson',
    headline: 'American actor, former professional wrestler and businessman',
    bio: 'Dwayne Johnson is an American actor and businessman. He is a former professional wrestler.',
    country: 'US',
    professions: ['actor', 'entrepreneur'],
    industries: ['film-tv'],
    topics: ['film', 'fitness'],
  },
  {
    name: 'Kylie Jenner',
    slug: 'kylie-jenner',
    wikiTitle: 'Kylie_Jenner',
    headline: 'American media personality and founder of Kylie Cosmetics',
    bio: 'Kylie Jenner is an American media personality and businesswoman. She is the founder of Kylie Cosmetics.',
    country: 'US',
    professions: ['entrepreneur'],
    industries: ['fashion-beauty'],
    topics: ['makeup', 'entrepreneurship'],
  },
  {
    name: 'Huda Kattan',
    slug: 'huda-kattan',
    wikiTitle: 'Huda_Kattan',
    headline: 'Beauty entrepreneur and founder of Huda Beauty',
    bio: 'Huda Kattan is a beauty entrepreneur. She is the founder of the cosmetics brand Huda Beauty.',
    country: 'US',
    professions: ['entrepreneur'],
    industries: ['fashion-beauty'],
    topics: ['makeup', 'skincare', 'entrepreneurship'],
  },
  {
    name: 'MrBeast',
    slug: 'mrbeast',
    wikiTitle: 'MrBeast',
    headline: 'American YouTuber known for large-scale challenge videos',
    bio: 'MrBeast, whose real name is Jimmy Donaldson, is an American YouTuber. He is known for large-scale challenge videos and philanthropy.',
    country: 'US',
    professions: ['youtuber'],
    industries: ['content-creation'],
    topics: ['philanthropy', 'social-media'],
  },
  {
    name: 'Emma Chamberlain',
    slug: 'emma-chamberlain',
    wikiTitle: 'Emma_Chamberlain',
    headline: 'American YouTuber, podcaster and founder of Chamberlain Coffee',
    bio: 'Emma Chamberlain is an American YouTuber and podcaster. She is the founder of Chamberlain Coffee.',
    country: 'US',
    professions: ['youtuber', 'entrepreneur'],
    industries: ['content-creation'],
    topics: ['lifestyle', 'podcasting'],
  },
  {
    name: 'Khaby Lame',
    slug: 'khaby-lame',
    wikiTitle: 'Khaby_Lame',
    headline: 'Senegalese-born Italian creator known for silent comedy videos',
    bio: 'Khaby Lame is a Senegalese-born Italian content creator. He is known for silent comedy videos on TikTok.',
    country: 'IT',
    professions: ['tiktoker'],
    industries: ['content-creation'],
    topics: ['comedy', 'social-media'],
  },
  {
    name: "Charli D'Amelio",
    slug: 'charli-damelio',
    wikiTitle: "Charli_D'Amelio",
    headline: 'American social media personality and dancer',
    bio: "Charli D'Amelio is an American social media personality and dancer.",
    country: 'US',
    professions: ['tiktoker'],
    industries: ['content-creation'],
    topics: ['dance', 'social-media'],
  },
  {
    name: 'Lilly Singh',
    slug: 'lilly-singh',
    wikiTitle: 'Lilly_Singh',
    headline: 'Canadian YouTuber, comedian and television host',
    bio: 'Lilly Singh is a Canadian YouTuber and comedian. She has also worked as a television host.',
    country: 'CA',
    professions: ['youtuber', 'public-speaker'],
    industries: ['content-creation'],
    topics: ['comedy', 'television'],
  },
  {
    name: 'Marques Brownlee',
    slug: 'marques-brownlee',
    wikiTitle: 'Marques_Brownlee',
    headline: 'American technology reviewer and YouTuber',
    bio: 'Marques Brownlee is an American YouTuber. He is known for reviewing consumer technology.',
    country: 'US',
    professions: ['youtuber'],
    industries: ['technology'],
    topics: ['tech-reviews'],
  },
  {
    name: 'Mark Rober',
    slug: 'mark-rober',
    wikiTitle: 'Mark_Rober',
    headline: 'American engineer, former NASA JPL engineer and science YouTuber',
    bio: "Mark Rober is an American engineer and science YouTuber. He previously worked as an engineer at NASA's Jet Propulsion Laboratory.",
    country: 'US',
    professions: ['youtuber'],
    industries: ['technology'],
    topics: ['engineering', 'science-communication'],
  },
  {
    name: 'Gary Vaynerchuk',
    slug: 'gary-vaynerchuk',
    wikiTitle: 'Gary_Vaynerchuk',
    headline: 'Belarus-born American entrepreneur and chairman of VaynerMedia',
    bio: 'Gary Vaynerchuk is a Belarus-born American entrepreneur. He is the chairman of VaynerMedia.',
    country: 'US',
    professions: ['entrepreneur', 'public-speaker'],
    industries: ['business-finance'],
    topics: ['entrepreneurship', 'digital-marketing'],
  },
]
