// Starter lists. Research team ki list aane pe yahan update karna
export const PROFESSIONS = [
  'Journalist',
  'News Anchor',
  'TV Host',
  'Actor',
  'Musician',
  'Content Creator',
  'YouTuber',
  'Podcaster',
  'Public Speaker',
  'Author',
  'Doctor',
  'Entrepreneur',
  'CEO / Executive',
  'Athlete',
  'Coach',
  'Chef',
  'Fashion Designer',
  'Photographer',
  'Artist',
  'Comedian',
  'Educator',
  'Scientist',
  'Lawyer',
  'Public Official',
  'Activist',
  'Religious Scholar',
  'Fitness Trainer',
  'Gamer / Streamer',
]

export const INDUSTRIES = [
  'Technology',
  'Media & News',
  'Entertainment',
  'Music',
  'Sports',
  'Health & Medicine',
  'Business & Finance',
  'Education',
  'Fashion & Beauty',
  'Food & Hospitality',
  'Travel & Tourism',
  'Gaming',
  'Politics & Government',
  'Non-profit & Social Impact',
  'Religion & Spirituality',
  'Real Estate',
  'Automotive',
  'Agriculture',
  'Art & Culture',
  'Science',
  'Law',
]

export const TOPICS = [
  'Artificial Intelligence',
  'Startups',
  'Cybersecurity',
  'Software Development',
  'Cricket',
  'Football',
  'Mental Health',
  'Nutrition',
  'Fitness',
  'Personal Finance',
  'Investing',
  'Crypto',
  'Climate Change',
  'Education Reform',
  'Women Empowerment',
  'Youth',
  'Parenting',
  'Comedy',
  'Drama',
  'Film',
  'Pop Music',
  'Qawwali',
  'Fashion Trends',
  'Skincare',
  'Cooking',
  'Street Food',
  'Travel',
  'Esports',
  'Politics',
  'Current Affairs',
  'Economy',
  'Digital Marketing',
  'Social Media',
  'Leadership',
  'Productivity',
  'Islamic Studies',
  'History',
  'Science Communication',
  'Space',
  'Public Health',
  'Human Rights',
  'Entrepreneurship',
  'E-commerce',
  'Freelancing',
  'Photography',
  'Books',
  'Poetry',
  'Urdu Literature',
  'Motivation',
]
